import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NavBar from "@/components/NavBar";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
<html lang="en" className="h-full">
      <body className="bg-[#0B1220] text-slate-100"> 
        {/* solid background only; no gradients */}
        <div className="px-4 sm:px-6 lg:px-8 py-5">
          {children}
        </div>
      </body>
    </html>
  );
}

// export default function RootLayout({ children }: { children: React.ReactNode }) {
//   return (
//     <html lang="en" className="h-full">
//       <body className="min-h-screen bg-slate-950 text-slate-100">
//         {/* Optional background gradient */}
//         <div className="pointer-events-none fixed inset-0 bg-gradient-to-b from-slate-900/0 via-slate-900/10 to-slate-900/0" />
//         <NavBar />
//         <div className="mx-auto max-w-7xl px-4 pt-6 pb-16">{children}</div>
//       </body>
//     </html>
//   );
// }
